name: transformer-deid
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyter
  - nltk
  - cudatoolkit
  - mpmath
  - numpy
  - pandas
  - pytest
  - pytorch
  - scikit-learn
  - spacy
  - sympy
  - tqdm
  - datasets
  - transformers
  - tokenizers
  - pytest
  - yapf
  - pip
  - pip:
    - seqeval
