name: transformer-deid
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyter
  - nltk
  - cudatoolkit=11.1
  - mpmath
  - numpy
  - pandas
  - pytest
  - pytorch
  - scikit-learn
  - spacy
  - sympy
  - tqdm
  - pytest
  - yapf
  - pip
  - pip:
    - transformers
